### ISSUE TITLE
How to read parsed data?

### ISSUE THREAD

**Issue by mevda** [bitcoinjs/fast-dat-parser#25]
Hello,

Thank you for this really fast block parser
May I ask you if this work fine for rev*.dat files too?
instead of
`cat ~/.bitcoin/blocks/blk*.dat | ./parser -j4 -t1 -wchain.dat > ~/.bitcoin/scripts.dat`
doing this (removing blk)
`cat ~/.bitcoin/blocks/*.dat | ./parser -j4 -t1 -wchain.dat > ~/.bitcoin/scripts.dat`

After I parsed all blocks how to read the data from scripts.dat file?

**Comment by mevda** [comment]
I found the answer to my first question here
https://bitcoin.stackexchange.com/questions/32716/what-exactly-are-the-rev00000-dat-files
I have scripts.dat file right now and it's big big file May I ask you how to read the scripts.dat file for extract information?

**Comment by dcousens** [comment]
> May I ask you if this work fine for rev*.dat files too?

I don't actually know to be honest.
I presume their format is different?

**Comment by dcousens** [comment]
> After I parsed all blocks how to read the data from scripts.dat file?

> 1 - Outputs every script prefixed with a uint16_t length

This is a binary format,  it mean there is a `uint16_t` (2 byte) length, and then a variable length array of data,  on repeat.
This may or may not be trivial to parse, depending on your experience with raw formats.
